logo = true
logoText = "MerrimanLab"
logoType = "short" # long, short
description = "Merriman Lab Notebook"

themeOptions = ["light", "dark"]

useFaviconGenerator = true # https://www.favicon-generator.org/

enableTocSwitch = true
enableSearch = true
enableSearchHighlight = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/MerrimanLab/"

# comment
enableComment = true
disqus_shortname = ""
commento = false
